language: python
python:
  - "3.6"
install:
  - pip install pipenv
  - pipenv install --dev
  - pip install pytest-xdist
script:
  - pytest -d --tx popen//python=python3.6
notifications:
  email:
    on_success: never
    on_failure: change

