language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install pipenv
  - pipenv install --dev
  - pip install pytest-xdist
script:
  - |
    if ["$TRAVIS_PYTHON_VERSION" = "3.5"]; then pytest -d --tx popen//python=python3.5; fi
    elif ["$TRAVIS_PYTHON_VERSION" = "3.6"]; then pytest -d --tx popen//python=python3.6; fi
    elif ["$TRAVIS_PYTHON_VERSION" = "3.7"]; then pytest -d --tx popen//python=python3.7; fi
notifications:
  email:
    on_success: never
    on_failure: change
deploy:
  provider: heroku
  api_key: "%token%"
  app:
    master: stella
    production: stella-dev
